apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    kubernetes.io/minikube-addons: registry
    addonmanager.kubernetes.io/mode: Reconcile
  name: registry
  namespace: kube-system
spec:
  replicas: 1
  selector:
    kubernetes.io/minikube-addons: registry
  template:
    metadata:
      labels:
        kubernetes.io/minikube-addons: registry
        addonmanager.kubernetes.io/mode: Reconcile
    spec:
      containers:
      - image: registry.hub.docker.com/library/registry:2.6.1
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
